data:
  image_dir: data/datasets/nuscenes/processed_10Hz/trainval2
  train_scene_list: data/datasets/nuscenes/processed_10Hz/trainval2/nuScenes_Train.txt
  val_scene_list: data/datasets/nuscenes/processed_10Hz/trainval2/nuScenes_Val.txt
  # true: old->new (0,1,2), false: new->old (2,1,0)
  multiframe_forward_order: true
  sequence_length: 3
  num_cameras_per_frame: 3
  target_size: 448
  max_interval: 5

model_init:
  aggregator_ckpt: checkpoints/recondrive/merged_ckpts/aggregator_merged.ckpt
  ego_pose_head_ckpt: checkpoints/DGGT_splitPtWeights/camera_head.pt # checkpoints/DGGT_splitPtWeights/camera_head.pt 
  aggregator_prefix: aggregator.
  ego_pose_head_prefix: camera_head. # camera_head. 
  aggregator_to_bfloat16: false
  use_camera_head_for_ego_pose: true

train:
  max_epoch: 3
  batch_size: 2
  num_workers: 16
  val_num_workers: 2

  # Legacy epoch-based keys (still supported as fallback): not used
  val_every: 1
  save_ckpt_every: 100

  # Preferred global-step keys:
  train_log_every_steps: 50
  val_every_steps: 1000
  save_ckpt_every_steps: 10000
  val_at_start: true

  lr: 4.0e-5
  weight_decay: 1.0e-4
  warmup_iterations: 1000

  trainable_modules:
    - ego_pose_head

  lr_per_module:
    ego_pose_head: 4.0e-5

  use_amp: true
  amp_dtype: bfloat16

loss:
  absolute_ego_pose_weight: 1.0
  T_loss_type: l1
  R_loss_type: l1
  stage_gamma: 0.6
  pose_encoding_type: absT_quaR

log:
  log_dir: logs/ego_pose_head_nuscenes
  tensorboard_subdir: tensorboard
  cal_flag: true
  debug_cal_every_steps: 1000
# 单卡
# CUDA_VISIBLE_DEVICES=3 torchrun --standalone --nnodes=1 --nproc_per_node=1 train_ego_pose_pred.py --config configs/train_ego_pose_pred_nuscenes.yaml

# 多卡
# CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --standalone --nnodes=1 --nproc_per_node=4 train_ego_pose_pred.py --config configs/train_ego_pose_pred_nuscenes.yaml
